name: API Stress Test Workflow

on: pull_request

jobs:
  check_comment_and_run_tests:
    if: github.event.issue.pull_request && contains(github.event.comment.body, 'trigger stress test')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository 
        uses: actions/checkout@v2

      - name: Set up Node.js 
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run stress tests 
        run: node stress-test.js
        continue-on-error: true 

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            ## Autocannon Stress Test Results
            ```
            $(cat results.txt)
            ```

