name: API Stress Test Workflow

on: pull_request

jobs:
  check_comment_and_run_tests:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository 
        uses: actions/checkout@v2

      - name: Set up Node.js 
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run stress tests 
        run: node stress-test.js
        continue-on-error: true 

      - name: Read test results
        id: test_results
        run: |
          echo "RESULT=$(cat result.txt)" >> $GITHUB_ENV

      - name: Comment PR
        uses: actions/github-script@v7
        with:
          script: |
            const result = process.env.RESULT;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: result
            })

